### ISSUE TITLE
run_mountainsort4 error when run in parallel 

### ISSUE THREAD

**Issue by MFVDias** [SpikeInterface/spikesorters#204]
Hello,
Not sure if this can be a ms4 problem but when I try to run it in parallel the following error is printed in the terminal over and over and no outputs are generated.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/spkinterface/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/anaconda3/envs/spkinterface/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/opt/anaconda3/envs/spkinterface/lib/python3.7/multiprocessing/spawn.py", line 220, in prepare
    set_start_method(data['start_method'], force=True)
  File "/opt/anaconda3/envs/spkinterface/lib/python3.7/multiprocessing/context.py", line 246, in set_start_method
    self._actual_context = self.get_context(method)
  File "/opt/anaconda3/envs/spkinterface/lib/python3.7/multiprocessing/context.py", line 238, in get_context
    return super().get_context(method)
  File "/opt/anaconda3/envs/spkinterface/lib/python3.7/multiprocessing/context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'loky'
```

I reinstalled 'spikesortes' from master but keep getting the same error.

**Comment by alejoe91** [comment]
Hi @MFVDias , 

Is this the entire error? I don't see where it's triggered within spikeinterface.. can you paste the full traceback?

**Comment by MFVDias** [comment]
Hi Alessio,

I only get that message on the terminal. 
After interrupting the code I get this one on my notebook

```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/joblib/parallel.py in retrieve(self)
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:

/opt/anaconda3/envs/spkinterface/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    429 
--> 430             self._condition.wait(timeout)
    431 

/opt/anaconda3/envs/spkinterface/lib/python3.7/threading.py in wait(self, timeout)
    295             if timeout is None:
--> 296                 waiter.acquire()
    297                 gotit = True

KeyboardInterrupt: 

During handling of the above exception, another exception occurred:

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-7-e93497b1781e> in <module>
     17                                 grouping_property='group',
     18                                 parallel=True,   # check if error!
---> 19                                 **default_ms4_params
     20                                 )
     21 

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/spikesorters/sorterlist.py in run_mountainsort4(*args, **kwargs)
    340         The spike sorted data
    341     """
--> 342     return run_sorter('mountainsort4', *args, **kwargs)
    343 
    344 

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/spikesorters/sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, verbose, raise_error, n_jobs, joblib_backend, **params)
     91                          verbose=verbose, delete_output_folder=delete_output_folder)
     92     sorter.set_params(**params)
---> 93     sorter.run(raise_error=raise_error, parallel=parallel, n_jobs=n_jobs, joblib_backend=joblib_backend)
     94     sortingextractor = sorter.get_result()
     95 

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/spikesorters/basesorter.py in run(self, raise_error, parallel, n_jobs, joblib_backend)
    160                 Parallel(n_jobs=n_jobs, backend=joblib_backend)(
    161                     delayed(self._run)(rec.dump_to_dict(), output_folder)
--> 162                     for (rec, output_folder) in zip(self.recording_list, self.output_folders))
    163 
    164             t1 = time.perf_counter()

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/joblib/parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/joblib/parallel.py in retrieve(self)
    953                     # scheduling.
    954                     ensure_ready = self._managed_backend
--> 955                     backend.abort_everything(ensure_ready=ensure_ready)
    956                 raise
    957 

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/joblib/_parallel_backends.py in abort_everything(self, ensure_ready)
    559         """Shutdown the workers and restart a new one with the same parameters
    560         """
--> 561         self._workers.terminate(kill_workers=True)
    562         self._workers = None
    563 

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/joblib/executor.py in terminate(self, kill_workers)
     72 
     73     def terminate(self, kill_workers=False):
---> 74         self.shutdown(kill_workers=kill_workers)
     75         if kill_workers:
     76             # When workers are killed in such a brutal manner, they cannot

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py in shutdown(self, wait, kill_workers)
   1169 
   1170         if executor_manager_thread is not None and wait:
-> 1171             executor_manager_thread.join()
   1172 
   1173         # To reduce the risk of opening too many files, remove references to

/opt/anaconda3/envs/spkinterface/lib/python3.7/threading.py in join(self, timeout)
   1042 
   1043         if timeout is None:
-> 1044             self._wait_for_tstate_lock()
   1045         else:
   1046             # the behavior of a negative timeout isn't documented, but

/opt/anaconda3/envs/spkinterface/lib/python3.7/threading.py in _wait_for_tstate_lock(self, block, timeout)
   1058         if lock is None:  # already determined that the C code is done
   1059             assert self._is_stopped
-> 1060         elif lock.acquire(block, timeout):
   1061             lock.release()
   1062             self._stop()

KeyboardInterrupt: 
```

**Comment by alejoe91** [comment]
Yeah it seems related to the `joblib` package not being able to spawn subprocesses with the `loky` context. Can you try to rerun it by adding the following arg to the `run_` function? `joblib_backend='multiprocessing'`

**Comment by MFVDias** [comment]
I'll give it try!

**Comment by MFVDias** [comment]
OK, now ms4 seems to be complaining 
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-13-d3ab03906393> in <module>
     19                                 parallel=True,   # check if error!
     20                                 joblib_backend='multiprocessing',
---> 21                                 **default_ms4_params
     22                                 )
     23 

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/spikesorters/sorterlist.py in run_mountainsort4(*args, **kwargs)
    340         The spike sorted data
    341     """
--> 342     return run_sorter('mountainsort4', *args, **kwargs)
    343 
    344 

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/spikesorters/sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, verbose, raise_error, n_jobs, joblib_backend, **params)
     91                          verbose=verbose, delete_output_folder=delete_output_folder)
     92     sorter.set_params(**params)
---> 93     sorter.run(raise_error=raise_error, parallel=parallel, n_jobs=n_jobs, joblib_backend=joblib_backend)
     94     sortingextractor = sorter.get_result()
     95 

/opt/anaconda3/envs/spkinterface/lib/python3.7/site-packages/spikesorters/basesorter.py in run(self, raise_error, parallel, n_jobs, joblib_backend)
    145 
    146         if parallel:
--> 147             assert self.compatible_with_parallel[joblib_backend], f"{self.sorter_name} is not compatible with " \
    148                                                                   f"joblib {joblib_backend} backend"
    149 

AssertionError: mountainsort4 is not compatible with joblib multiprocessing backend
```

**Comment by alejoe91** [comment]
Right.. in fact MS4 is set to only work with `loky` now that I double checked. 
For now I would run it with `parallel=False`. 

What OS are you running? The `parallel` option is tested in Ubuntu, but it might not work well with other OS

**Comment by MFVDias** [comment]
Thanks for the quick reply. I'm on a Mac.

Running with `parallel=False` works fine but takes a lot of time.

**Comment by vojtasmekal** [comment]
Hi, 
I seem to be having the same issue when running ms4, but I'm not sure I understand where to include the `parallel=False` parameter. 
Thanks in advance!
