### ISSUE TITLE
TrideSclous results may contain empty array

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [SpikeInterface/spikesorters#56]
When running TrideSclous sorter on dataset from tutorial, I found that the results contain empty numpy array and thus cause value error in line 845 of Spiketools.postprocessing.postprocessing_tools.py (function: _get_random_spike_waveforms).

Fix todo:
1. append a value checker at line 53 in sorterlist.py (function: run_sorter) to remove empty units.

**Comment by samuelgarcia** [comment]
Thanks.
I think a spiketrain with no spike is a valid situation.
When we get waveforms from this it should return an array with shape (0, numchan, numsample).
I think it is a better approach to just the remove the empty units.

**Comment by Shawn-Guo-CN** [comment]
Update another potential effect of the empty array:

it may cause a value error in line 291, SpikeComparison\comparisiontools.py (function: make_best_match), as np.argmax() is called at that line.

The traceback is:
```python
Traceback (most recent call last):
  File "e:/projects/shawn/tutorial.py", line 169, in <module>
    cmp_agr_gt = sc.compare_sorter_to_ground_truth(sorting_gt, sorting_agreement)
  File "e:\projects\spikecomparison\spikecomparison\groundtruthcomparison.py", line 462, in compare_sorter_to_ground_truth
    verbose=verbose)
  File "e:\projects\spikecomparison\spikecomparison\groundtruthcomparison.py", line 41, in __init__
    verbose=verbose)
  File "e:\projects\spikecomparison\spikecomparison\basecomparison.py", line 74, in __init__
    self._do_matching()
  File "e:\projects\spikecomparison\spikecomparison\groundtruthcomparison.py", line 84, in _do_matching
    self.best_match_12, self.best_match_21 = make_best_match(self.agreement_scores, self.min_accuracy)
  File "e:\projects\spikecomparison\spikecomparison\comparisontools.py", line 291, in make_best_match
    ind_max = np.argmax(scores[i1, :])
  File "<__array_function__ internals>", line 6, in argmax
  File "D:\Anaconda3\envs\spike_dev\lib\site-packages\numpy\core\fromnumeric.py", line 1153, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "D:\Anaconda3\envs\spike_dev\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
```

**Comment by alejoe91** [comment]
I just ran into the same error in spikecomparison. I think we should deal with it at the spikesorters level. Are there no units at all?

**Comment by alejoe91** [comment]
(try to upgrade tridesclous to the latest version as well - 1.2.2)

**Comment by Shawn-Guo-CN** [comment]
> I just ran into the same error in spikecomparison. I think we should deal with it at the spikesorters level. Are there no units at all?

Yep, shape of spike train from the corresponding unit is (0, 16, 96).

**Comment by samuelgarcia** [comment]
I really think it is a bad approach.
A sorter could find a cluster and then if template matching could find no spike at all in this cluster for other reasons. They should not be remove we could bias comparison we must consolidate our code.
We already have tools to clean this case I don't think we must impose it at run sorter level.
